apiVersion: v1
kind: Namespace
metadata:
  name: anne-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: anne-namespace
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: anne07/flask
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
